local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

return {
  s("pwn", {
    t({
      "#!/usr/bin/env python3",
      "from pwn import *",
      "",
      "exe = context.binary = ELF('./",
    }),
    i(1, "your_binary"),
    t({
      "', checksec=False)",
      'context.terminal = ["tmux", "splitw", "-h"]',
      "",
      "if exe.bits == 32:",
      '    lindbg = "/home/nosurfer/ida-pro-9.0/dbgsrv/linux_server32"',
      "else:",
      '    lindbg = "/home/nosurfer/ida-pro-9.0/dbgsrv/linux_server"',
      "",
      'host = args.HOST or "',
    }),
    i(2, "127.0.0.1"),
    t({
      '"',
      "port = int(args.PORT or ",
    }),
    i(3, "1234"),
    t({
      ")",
      "",
      "def local(argv=[], *a, **kw):",
      "    if args.GDB:",
      "        return gdb.debug([exe.path] + argv, gdbscript=gdbscript, *a, **kw)",
      "    elif args.IDA:",
      "        return process([lindbg], *a, **kw)",
      "    else:",
      "        return process([exe.path] + argv, *a, **kw)",
      "",
      "def remote(argv=[], *a, **kw):",
      "    io = connect(host, port)",
      "    if args.GDB:",
      "        gdb.attach(io, gdbscript=gdbscript)",
      "    return io",
      "",
      "def start(argv=[], *a, **kw):",
      "    if args.REMOTE:",
      "        return remote(argv, *a, **kw)",
      "    else:",
      "        return local(argv, *a, **kw)",
      "",
      'gdbscript = """',
      "tb main",
      "c",
      '""".format(**locals())',
      "",
      "info = lambda msg: log.info(msg)",
      "success = lambda msg: log.success(msg)",
      "warn = lambda msg: io.warn(msg)",
      "sla = lambda msg, data: io.sendlineafter(msg, data)",
      "sa = lambda msg, data: io.sendafter(msg, data)",
      "sl = lambda data: io.sendline(data)",
      "s = lambda data: io.send(data)",
      "ru = lambda msg: io.recvuntil(msg)",
      "",
      "io = start()",
      "",
      "io.interactive()",
      "",
    }),
  }),
}
